FROM python:3.6-alpine

ENV LC_ALL C.UTF-8
ENV LANG C.UTF-8

RUN pip3 install -U pip
RUN pip3 install pipenv

RUN apk add --no-cache \
    libev \
    python3 py-pip \
    python3-dev build-base \
&& pip3 install gevent gunicorn \
&& apk del python3-dev build-base

RUN apk add postgresql-libs && \
    apk add --virtual .build-deps gcc musl-dev postgresql-dev && \
    pip3 install psycopg2 psycopg2-binary && \
    apk --purge del .build-deps


CMD ["python3"]