FROM python:3.6-alpine

ENV LC_ALL C.UTF-8
ENV LANG C.UTF-8

RUN pip3 install -U pip
RUN pip3 install pipenv

RUN apk add --no-cache \
    libev \
    python py-pip \
    python-dev build-base \
&& pip install gevent gunicorn \
&& apk del python-dev build-base


CMD ["python3"]