FROM nvidia/cuda:9.0-cudnn7-runtime

RUN apt-get update && apt-get install -y \
		python3 \
		python3-dev \
		python3-pip\
		&& \
	apt-get clean && \
	apt-get autoremove && \
	rm -rf /var/lib/apt/lists/*

ENV LC_ALL C.UTF-8
ENV LANG C.UTF-8

RUN pip3 install -U pip
RUN pip3 install pipenv

CMD [ "python3" ]